name: Release wheels

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - manylinux2014_x86_64
        python-version:
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
    container: quay.io/pypa/${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install system dependencies
      run: |
        yum --disablerepo=epel install -y fontconfig-devel mesa-libGL-devel xorg-x11-server-Xvfb mesa-dri-drivers
        yum clean all
        rm -rf /var/cache/yum
    - name: Set PATH
      run: echo "$PWD/depot_tools" >> $GITHUB_PATH
    - name: Build gn
      env:
        CC: gcc
        CXX: g++
        AR: ar
        CFLAGS: -Wno-deprecated-copy
        LDFLAGS: -lrt
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        git checkout 981f46c64d1456d2083b1a2fa1367e753e0cdc1b
        python build/gen.py
        ninja -C out gn
        cd ..
    - name: Build Skia
      run: |
        echo "++++++++++++++PWD: ${PWD}++++++++++++++"
        ls -lh .
        cd skia
        patch -p1 < ../patch/git-sync-deps.patch
        python tools/git-sync-deps
        cp -f ../gn/out/gn bin/gn  # Replace gn.
        bin/gn gen out/Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false extra_cflags_cc=["-frtti"] extra_ldflags=["-lrt"]'
        ninja -C out/Release skia skia.h experimental_svg_model
        cd ..
    - name: Set up Python
      run: echo "/opt/python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
    - name: Build python binding
      run: |
        python -m pip install -U pip
        python -m pip install --no-cache-dir pybind11 numpy wheel twine
        python -m pip wheel . -w dist --no-deps --verbose
        auditwheel repair dist/skia*.whl -w wheelhouse
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing wheelhouse/*
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set PATH
      run: echo "$PWD/depot_tools" >> $GITHUB_PATH
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        bin/gn gen out/Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false extra_cflags_cc=["-frtti", "-mmacosx-version-min=10.9"]'
        ninja -C out/Release skia skia.h experimental_svg_model
        cd ..
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build python binding
      env:
        CC: clang
        CXX: clang++
      run: |
        python -m pip install -U pip
        python -m pip install --no-cache-dir pybind11 numpy wheel twine
        python -m pip wheel . -w wheelhouse --no-deps
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing wheelhouse/*
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x64 ]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set PATH
      run: echo "$pwd\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Build Skia
      run: |
        cd skia
        python tools\git-sync-deps
        bin\gn gen out\Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false skia_use_system_expat=false skia_use_system_zlib=false extra_cflags_cc=[\"/GR\", \"/EHsc\", \"/MD\"] target_cpu=\"${{ matrix.arch }}\"'
        ninja -C out\Release skia skia.h experimental_svg_model
        cd ..
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build python binding
      env:
        DISTUTILS_USE_SDK: 1
      run: |
        $path = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        $args = '-arch=${{ matrix.arch }}'
        if ($path) {
            $path = join-path $path 'Common7\Tools\vsdevcmd.bat'
            if (test-path $path) {
                cmd /s /c """$path"" $args && set" | where { $_ -match '(\w+)=(.*)' } | foreach {
                    $null = new-item -force -path "Env:\$($Matches[1])" -value $Matches[2]
                }
            }
        }
        python -m pip install -U pip
        python -m pip install --no-cache-dir pybind11 numpy wheel twine
        python -m pip wheel . -w wheelhouse --no-deps
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing wheelhouse\*
